// This file is automatically generated from '../src/@CFB_Skins/addons/cfb_skins/groups_tw.hpp'.
// Do not hand-edit.

class CFB_Groups_AR
{
	name = "Infantry (CADPAT AR)";
	class CFB_Groups_AR_Rifle_Section
	{
		faction = "CFB_Base_Faction";
		name = "Rifle Section";
		side = 1;

		class Unit0 { side = 1; vehicle = "CFB_AR_Soldier_TL"; rank = "SERGEANT"; position[] = {0,0,0}; };
		class Unit1 { side = 1; vehicle = "CFB_AR_Soldier_GL"; rank = "PRIVATE"; position[] = {5,-5,0}; };
		class Unit2 { side = 1; vehicle = "CFB_AR_Soldier_AR"; rank = "PRIVATE"; position[] = {-5,-5,0}; };
		class Unit3 { side = 1; vehicle = "CFB_AR_Soldier_LAT"; rank = "PRIVATE"; position[] = {10,-10,0}; };
		
		class Unit4 { side = 1; vehicle = "CFB_AR_Soldier_TL"; rank = "CORPORAL"; position[] = {-10,-10,0}; };
		class Unit5 { side = 1; vehicle = "CFB_AR_Soldier_Medic"; rank = "PRIVATE"; position[] = {15,-15,0}; };
		class Unit6 { side = 1; vehicle = "CFB_AR_Soldier_AR"; rank = "PRIVATE"; position[] = {-15,-15,0}; };
		class Unit7 { side = 1; vehicle = "CFB_AR_Soldier_Marksman"; rank = "PRIVATE"; position[] = {20,-20,0}; };
	};
	
	class CFB_Groups_AR_Rifle_Assault_Team
	{
		faction = "CFB_Base_Faction";
		name = "Assault Group 1";
		side = 1;

		class Unit0 { side = 1; vehicle = "CFB_AR_Soldier_TL"; rank = "SERGEANT"; position[] = {0,0,0}; };
		class Unit1 { side = 1; vehicle = "CFB_AR_Soldier_GL"; rank = "PRIVATE"; position[] = {5,-5,0}; };
		class Unit2 { side = 1; vehicle = "CFB_AR_Soldier_AR"; rank = "PRIVATE"; position[] = {-5,-5,0}; };
		class Unit3 { side = 1; vehicle = "CFB_AR_Soldier_LAT"; rank = "PRIVATE"; position[] = {10,-10,0}; };
	};
	
	class CFB_Groups_AR_Support_Assault_Team
	{
		faction = "CFB_Base_Faction";
		name = "Assault Group 2 (Support)";
		side = 1;

		class Unit0 { side = 1; vehicle = "CFB_AR_Soldier_TL"; rank = "SERGEANT"; position[] = {0,0,0}; };
		class Unit1 { side = 1; vehicle = "CFB_AR_Soldier_Medic"; rank = "PRIVATE"; position[] = {5,-5,0}; };
		class Unit2 { side = 1; vehicle = "CFB_AR_Soldier_AR"; rank = "PRIVATE"; position[] = {-5,-5,0}; };
		class Unit3 { side = 1; vehicle = "CFB_AR_Soldier_Marksman"; rank = "PRIVATE"; position[] = {10,-10,0}; };
	};
	
	class CFB_Groups_AR_MMG_Team
	{
		faction = "CFB_Base_Faction";
		name = "MMG Weapon Group";
		side = 1;

		class Unit0 { side = 1; vehicle = "CFB_AR_Soldier_MMG"; rank = "CORPORAL"; position[] = {0,0,0}; };
		class Unit1 { side = 1; vehicle = "CFB_AR_Soldier"; rank = "PRIVATE"; position[] = {5,-5,0}; };
		class Unit2 { side = 1; vehicle = "CFB_AR_Soldier"; rank = "PRIVATE"; position[] = {-5,-5,0}; };
	};
	
	class CFB_Groups_AR_AT_Team
	{
		faction = "CFB_Base_Faction";
		name = "AT Missile Group";
		side = 1;
		
		class Unit0 { side = 1; vehicle = "CFB_AR_Soldier_AT"; rank = "CORPORAL"; position[] = {0,0,0}; };
		class Unit1 { side = 1; vehicle = "CFB_AR_Soldier_AT"; rank = "PRIVATE"; position[] = {5,-5,0}; };
		class Unit2 { side = 1; vehicle = "CFB_AR_Soldier_AmmoBearer_AT"; rank = "PRIVATE"; position[] = {-5,-5,0}; };
	};
	
	class CFB_Groups_AR_AA_Team
	{
		faction = "CFB_Base_Faction";
		name = "AA Missile Group";
		side = 1;
		
		class Unit0 { side = 1; vehicle = "CFB_AR_Soldier_AA"; rank = "CORPORAL"; position[] = {0,0,0}; };
		class Unit1 { side = 1; vehicle = "CFB_AR_Soldier_AA"; rank = "PRIVATE"; position[] = {5,-5,0}; };
		class Unit2 { side = 1; vehicle = "CFB_AR_Soldier_AmmoBearer_AA"; rank = "PRIVATE"; position[] = {-5,-5,0}; };
	};
	
	class CFB_Groups_AR_Engineer_Team
	{
		faction = "CFB_Base_Faction";
		name = "Engineer Group";
		side = 1;
		
		class Unit0 { side = 1; vehicle = "CFB_AR_Soldier_Engineer"; rank = "CORPORAL"; position[] = {0,0,0}; };
		class Unit1 { side = 1; vehicle = "CFB_AR_Soldier_Engineer"; rank = "PRIVATE"; position[] = {5,-5,0}; };
		class Unit2 { side = 1; vehicle = "CFB_AR_Soldier_Engineer"; rank = "PRIVATE"; position[] = {-5,-5,0}; };
	};
	
	class CFB_Groups_AR_Sentry
	{
		faction = "CFB_Base_Faction";
		name = "Sentry Team";
		side = 1;
		
		class Unit0 { side = 1; vehicle = "CFB_AR_Soldier"; rank = "CORPORAL"; position[] = {0,0,0}; };
		class Unit1 { side = 1; vehicle = "CFB_AR_Soldier_GL"; rank = "PRIVATE"; position[] = {5,-5,0}; };
	};
	
	class CFB_Groups_AR_Marksman_Team
	{
		faction = "CFB_Base_Faction";
		name = "Marksman Team";
		side = 1;

		class Unit0 { side = 1; vehicle = "CFB_AR_Soldier_TL"; rank = "CORPORAL"; position[] = {0,0,0}; };
		class Unit1 { side = 1; vehicle = "CFB_AR_Soldier_Marksman"; rank = "PRIVATE"; position[] = {5,-5,0}; };
	};
};
