// This file is automatically generated from '../src/@CFB_Skins/addons/cfb_skins/weapons_vests_tw.hpp'.
// Do not hand-edit.

// class V_TacVest_oli;
class CFB_AR_Vest_Tactical : V_TacVest_oli
{
	side = 1;
	scope = 2;
	scopeCurator = 2;
	displayName = "CADPAT AR Tactical Vest";
	author = "Anton Struyk";
	picture = "\cfb_skins\ui\CFB_AR_Vest_Tactical.paa";
	hiddenSelections[] = {"camo"};
	hiddenSelectionsTextures[] = {"\cfb_skins\CADPAT_AR_Vest_Tactical.paa"};
};

// class V_PlateCarrier1_rgr;
class CFB_AR_Vest_PlateCarrier1 : V_PlateCarrier1_rgr
{
	side = 1;
	scope = 2;
	scopeCurator = 2;
	displayName = "CADPAT AR Plate Carrier Lite";
	author = "Anton Struyk";
	picture = "\cfb_skins\ui\CFB_AR_Vest_PlateCarrier1.paa";
	hiddenSelections[] = {"camo"};
	hiddenSelectionsTextures[] = {"\cfb_skins\CADPAT_AR_Vest_NATO.paa"};
	class ItemInfo : ItemInfo
	{
		hiddenSelections[] = {"camo"};
	};
};

// class V_PlateCarrier2_rgr;
class CFB_AR_Vest_PlateCarrier2 : V_PlateCarrier2_rgr
{
	side = 1;
	scope = 2;
	scopeCurator = 2;
	displayName = "CADPAT AR Plate Carrier";
	author = "Anton Struyk";
	picture = "\cfb_skins\ui\CFB_AR_Vest_PlateCarrier2.paa";
	hiddenSelections[] = {"camo"};
	hiddenSelectionsTextures[] = {"\cfb_skins\CADPAT_AR_Vest_NATO.paa"};
	class ItemInfo : ItemInfo
	{
		hiddenSelections[] = {"camo"};
	};
};
