// This file is automatically generated from '../src/@CFB_Skins/addons/cfb_skins/weapons_headgear_tw.hpp'.
// Do not hand-edit.

// class H_HelmetIA;
class CFB_AR_Helmet : H_HelmetIA
{
	side = 1;
	scope = 2;
	scopeCurator = 2;
	displayName = "CADPAT AR Helmet";
	picture = "\cfb_skins\ui\CFB_AR_Helmet.paa";
	author = "Anton Struyk";
	hiddenSelections[] = {"camo"};
	hiddenSelectionsTextures[] = {"\cfb_skins\CADPAT_AR_Helmet_AAF.paa"};
};

// class H_Booniehat_tan;
class CFB_AR_Boonie : H_Booniehat_tan
{
	side = 1;
	scope = 2;
	scopeCurator = 2;
	displayName = "CADPAT AR Boonie Hat";
	picture = "\cfb_skins\ui\CFB_AR_Boonie.paa";
	author = "Anton Struyk";
	hiddenSelections[] = {"camo"};
	hiddenSelectionsTextures[] = {"\cfb_skins\CADPAT_AR_Hat_Boonie.paa"};
};

// class H_MilCap_gry;
class CFB_AR_Patrol : H_MilCap_gry
{
	side = 1;
	scope = 2;
	scopeCurator = 2;
	displayName = "CADPAT AR Patrol Hat";
	picture = "\cfb_skins\ui\CFB_AR_Patrol.paa";
	author = "Anton Struyk";
	hiddenSelections[] = {"camo"};
	hiddenSelectionsTextures[] = {"\cfb_skins\CADPAT_AR_Hat_Patrol.paa"};
};

// class H_HelmetB;
class CFB_AR_Helmet_ECH : H_HelmetB
{
	side = 1;
	scope = 2;
	scopeCurator = 2;
	displayName = "CADPAT AR ECH Helmet";
	picture = "\cfb_skins\ui\CFB_AR_Helmet_ECH.paa";
	author = "Anton Struyk";
	hiddenSelections[] = {"camo"};
	hiddenSelectionsTextures[] = {"\cfb_skins\CADPAT_AR_Helmet_ECH.paa"};
};